development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: recipes_development
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: recipes_test
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock
